In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('flujo-vehicular-por-radares-2025.csv', sep=';', encoding='latin1')
df.head()

,"Día, Mes, Año de H_Fecha",Hora de H_Fecha,Aut Nombre,Disp Nombre,Disp Ubicacion,Seccion Sentido,Disp Lat,Disp Lng,H_Cant_Veh
0,1/1/2025,0.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",1317.0
1,1/1/2025,1.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",4863.0
2,1/1/2025,2.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",5808.0
3,1/1/2025,3.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",3293.0
4,1/1/2025,4.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",1632.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607073 entries, 0 to 607072
Data columns (total 9 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Día, Mes, Año de H_Fecha  607062 non-null  object
 1   Hora de H_Fecha           607062 non-null  float64
 2   Aut Nombre                607062 non-null  object
 3   Disp Nombre               607062 non-null  object
 4   Disp Ubicacion            607062 non-null  object
 5   Seccion Sentido           605843 non-null  object
 6   Disp Lat                  607062 non-null  object
 7   Disp Lng                  607062 non-null  object
 8   H_Cant_Veh                607062 non-null  float64
dtypes: float64(2), object(7)
memory usage: 41.7+ MB

In [7]:
df['Día, Mes, Año de H_Fecha'] = pd.to_datetime(df['Día, Mes, Año de H_Fecha'], format='%d/%m/%Y', errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607073 entries, 0 to 607072
Data columns (total 9 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Día, Mes, Año de H_Fecha  597666 non-null  datetime64[ns]
 1   Hora de H_Fecha           607062 non-null  float64
 2   Aut Nombre                607062 non-null  object
 3   Disp Nombre               607062 non-null  object
 4   Disp Ubicacion            607062 non-null  object
 5   Seccion Sentido           605843 non-null  object
 6   Disp Lat                  607062 non-null  object
 7   Disp Lng                  607062 non-null  object
 8   H_Cant_Veh                607062 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 41.7+ MB

In [9]:
print("Max date:", df['Día, Mes, Año de H_Fecha'].max().date())

Max date: 2025-12-31

In [10]:
df.columns

Index(['Día, Mes, Año de H_Fecha', 'Hora de H_Fecha', 'Aut Nombre',
       'Disp Nombre', 'Disp Ubicacion', 'Seccion Sentido', 'Disp Lat',
       'Disp Lng', 'H_Cant_Veh'],
      dtype='object')

In [16]:
df25=pd.read_csv('flujo-vehicular-por-radares-2025.csv', sep=';', encoding='latin1')
df24=pd.read_csv('flujo-vehicular-por-radares-2024.csv', sep=';', encoding='latin1')
df23=pd.read_csv('flujo-vehicular-por-radares-2023.csv', sep=';', encoding='latin1')
df22=pd.read_csv('flujo-vehicular-por-radares-2022.csv', sep=';', encoding='latin1')
df21=pd.read_csv('flujo-vehicular-por-radares-2021.csv', sep=';', encoding='latin1')
df20=pd.read_csv('flujo-vehicular-por-radares-2020.csv', sep=',', encoding='latin1')
df19=pd.read_csv('flujo-vehicular-por-radares-2019.csv', sep=',', encoding='latin1')

C:\Users\santi\AppData\Local\Temp\ipykernel_20056\446497687.py:5: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df21=pd.read_csv('flujo-vehicular-por-radares-2021.csv', sep=';', encoding='latin1')

In [12]:
df24.head()

,"Día, Mes, Año de H_Fecha",Hora de H_Fecha,Aut Nombre,Disp Nombre,Disp Ubicacion,Seccion Sentido,Disp Lat,Disp Lng,H_Cant_Veh
0,1/1/2024,0.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",1344.0
1,1/1/2024,1.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",4798.0
2,1/1/2024,2.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",5522.0
3,1/1/2024,3.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",3452.0
4,1/1/2024,4.0,AU 4 Lugones,RD171 Esma,"9,9",A,"-34,53767","-58,45967",1700.0

In [17]:
df21.head()

             Mes DÃ­a AÃ±o de H_Fecha      H_Hora Aut Nombre Disp Nombre  \
1/1/2021 0.0            AU 4  Lugones  RD171 Esma        9.9           A
         1.0            AU 4  Lugones  RD171 Esma        9.9           A
         2.0            AU 4  Lugones  RD171 Esma        9.9           A
         3.0            AU 4  Lugones  RD171 Esma        9.9           A
         4.0            AU 4  Lugones  RD171 Esma        9.9           A

             Disp Ubicacion          Seccion Sentido  Disp Lat  Disp Lng  \
1/1/2021 0.0            NaN  -58.459.669.999.999.900       943       NaN
         1.0            NaN  -58.459.669.999.999.900      3946       NaN
         2.0            NaN  -58.459.669.999.999.900      4662       NaN
         3.0            NaN  -58.459.669.999.999.900      2486       NaN
         4.0            NaN  -58.459.669.999.999.900      1268       NaN

              H_Cant_Veh  Hora de H_Fecha
1/1/2021 0.0         NaN              NaN
         1.0         NaN              NaN
         2.0         NaN              NaN
         3.0         NaN              NaN
         4.0         NaN              NaN